const {chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE});
const page=await browser.newPage({viewport:{width:1440,height:900}});
await page.goto('http://127.0.0.1:8791');
const fixtures=await page.evaluate(()=>{
 const c=document.createElement('canvas');c.width=c.height=100;const x=c.getContext('2d');
 x.fillStyle='#ef8040';x.fillRect(0,0,100,100);const preview=c.toDataURL();
 x.fillStyle='black';x.fillRect(0,0,100,100);x.fillStyle='white';x.fillRect(25,25,50,50);
 return {preview,mask:c.toDataURL()};
});
let exports=0;
await page.route('**/api/images',r=>r.fulfill({json:{session_id:'fixture',width:100,height:100,preview:fixtures.preview}}));
await page.route('**/api/segment',r=>r.fulfill({json:{mask:fixtures.mask}}));
page.on('request',r=>{if(r.url().includes('/api/export/'))exports++});
await page.locator('#fileInput').setInputFiles({name:'fixture.png',mimeType:'image/png',buffer:Buffer.from(fixtures.preview.split(',')[1],'base64')});
await page.waitForFunction(()=>document.querySelector('#imageCanvas').width>100);
if(await page.locator('#emptyState').isVisible())throw Error('导入后空白页提示仍显示');
const before=await page.locator('#imageCanvas').evaluate(c=>c.getContext('2d').getImageData(5,5,1,1).data[3]);
if(before!==255)throw Error('导入后原图不可见');
await page.locator('#maskCanvas').click();
await page.waitForFunction(()=>!document.querySelector('#cutoutExportButton').disabled);
const pixels=await page.evaluate(()=>{
const c=document.querySelector('#maskCanvas'),x=c.getContext('2d');
const composite=document.createElement('canvas');composite.width=c.width;composite.height=c.height;
const ctx=composite.getContext('2d');ctx.drawImage(document.querySelector('#imageCanvas'),0,0);ctx.drawImage(c,0,0);
const dark=ctx.getImageData(5,5,1,1).data[0],bright=ctx.getImageData(c.width*.4,c.height*.4,1,1).data[0];
if(dark<75||dark>90||bright!==239)throw Error('背景未压暗或前景被变暗: '+dark+','+bright);
return {dark,bright,background:x.getImageData(5,5,1,1).data[3],foreground:x.getImageData(c.width*.4,c.height*.4,1,1).data[3],base:document.querySelector('#imageCanvas').getContext('2d').getImageData(5,5,1,1).data[3]};
});
if(pixels.background!==0||pixels.foreground!==255||pixels.base!==255||exports)throw Error(JSON.stringify({pixels,exports}));
const nextRequest=page.waitForRequest(r=>r.url().includes('/api/segment'));
await page.locator('#edgeShift').evaluate(el=>{el.value='-4';el.dispatchEvent(new Event('input',{bubbles:true}))});
const sent=(await nextRequest).postDataJSON();
if(sent.edge_shift!==-4)throw Error('边缘参数未传到后端');
if(await page.locator('#edgeShiftValue').textContent()!=='-4 px')throw Error('边缘数值未更新');
await page.waitForFunction(()=>!document.querySelector('#cutoutExportButton').disabled);
const box=await page.locator('#maskCanvas').boundingBox();
const anchor={x:box.x+box.width*.4,y:box.y+box.height*.4};
await page.mouse.move(anchor.x,anchor.y);await page.mouse.wheel(0,-300);
await page.waitForFunction(()=>document.querySelector('#zoomValue').textContent!=='100%');
const enlarged=await page.locator('#maskCanvas').boundingBox();
if(Math.abs((anchor.x-enlarged.x)/enlarged.width-.4)>.002)throw Error('缩放锚点漂移');
const mapped=page.waitForRequest(r=>r.url().includes('/api/segment'));
await page.mouse.click(anchor.x,anchor.y);
const point=(await mapped).postDataJSON().points[0];
if(point.x!==40||point.y!==40)throw Error('缩放后点选坐标错误');
await page.waitForFunction(()=>!document.querySelector('#cutoutExportButton').disabled);
let panRequests=0;const watch=r=>{if(r.url().includes('/api/segment'))panRequests++};page.on('request',watch);
await page.keyboard.down('Space');await page.mouse.move(anchor.x,anchor.y);
await page.mouse.down();await page.mouse.move(anchor.x+60,anchor.y+35,{steps:5});await page.mouse.up();await page.keyboard.up('Space');
const moved=await page.locator('#maskCanvas').boundingBox();
if(Math.abs(moved.x-enlarged.x-60)>1||Math.abs(moved.y-enlarged.y-35)>1||panRequests)throw Error('平移失败或误点选');
await page.locator('#fitButton').click();
if(await page.locator('#zoomValue').textContent()!=='100%')throw Error('重置失败');
console.log(JSON.stringify({pixels,point,panRequests,result:'PASS zoom/pan'}));
await page.locator('#zoomSlider').evaluate(el=>{el.value='200';el.dispatchEvent(new Event('input',{bubbles:true}))});
if(await page.locator('#zoomValue').textContent()!=='200%')throw Error('缩放滑块无效');
await page.setViewportSize({width:760,height:700});
for(const id of ['zoomSlider','edgeShift']){
 await page.locator('#'+id).scrollIntoViewIfNeeded();
 if(!await page.locator('#'+id).isVisible())throw Error('窄窗口滑块隐藏: '+id);
}
console.log('PASS visible controls at 760x700, slider 200%');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
