const assert = require('node:assert/strict');
const fs = require('node:fs');
const nodePath = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
    const browser = await chromium.launch({headless:true, channel:'chrome'});
    try {
        const page = await browser.newPage({viewport:{width:1500,height:900}});
        await page.addInitScript(() => localStorage.setItem('studio_theme','dark'));
        const calls = [];
        let uploadCount = 0;
        await page.route('**/api/**', async route => {
            const url = new URL(route.request().url());
            const path = url.pathname;
            const request = route.request();
            if(path === '/api/ecommerce/capabilities') return route.fulfill({json:{models:[{provider_id:'demo',model:'demo-image'}],providers:[{id:'demo',name:'Demo'}],routes:{standard:{provider_id:'demo',model:'demo-image'}},vision_analysis:{enabled:true},reference_slot_types:[]}});
            if(path === '/api/ai/upload') { const name=['model.png','model.png','model.png','blazer.png','trousers.png','loafers.png','blazer-detail.png','blazer.png'][uploadCount++] || 'blazer.png'; const localAsset=nodePath.join('.codex-tmp/tryon-steps-demo/assets',name); const imageUrl=fs.existsSync(localAsset) ? `/${localAsset.replaceAll('\\','/')}?reference=${uploadCount}` : `/static/images/logo.png?reference=${uploadCount}`; return route.fulfill({json:{files:[{url:imageUrl,kind:'image',width:512,height:512,name}]}}); }
            if(path === '/api/ecommerce/analyze') { calls.push({path, body:request.postDataJSON()}); return route.fulfill({json:{status:'succeeded',message:'视觉分析完成',prompt_preview:'人物身份锁定；保留上装材质和颜色；完成真实试穿。',analysis:{status:'succeeded',category:'upper'},reference_plan:{ordered_reference_ids:['source','upper_garment']}}}); }
            if(path === '/api/ecommerce/tasks' && request.method() === 'POST') { const body=request.postDataJSON(); calls.push({path, body}); const id=body.operation === 'try_on' ? 'tryon-demo' : 'guide-demo'; return route.fulfill({json:{id,task_id:id,operation:body.operation,status:'queued',result:null}}); }
            if(path === '/api/ecommerce/tasks/guide-demo') return route.fulfill({json:{id:'guide-demo',task_id:'guide-demo',operation:'universal',status:'succeeded',result:{images:['/static/images/logo.png']}}});
            if(path === '/api/ecommerce/tasks/tryon-demo') return route.fulfill({json:{id:'tryon-demo',task_id:'tryon-demo',operation:'try_on',status:'succeeded',result:{images:['/static/images/logo.png']}}});
            if(path === '/api/ecommerce/tasks') return route.fulfill({json:{tasks:[]}});
            return route.fulfill({json:{}});
        });
        await page.goto('http://127.0.0.1:8765/static/ecommerce.html');
        await page.locator('[data-operation="try_on"]').click();
        await page.locator('.ec-tryon-stepbar [data-tryon-step="0"]').waitFor();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-model').count(),1);
        assert.equal(await page.locator('.ec-tryon-slot-card.is-outfit').count(),0);
        await page.locator('[data-tryon-step-next]').click();
        assert.equal(await page.locator('.ec-tryon-stepbar [data-tryon-step="0"].active').count(),1);
        const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lXcAAAAASUVORK5CYII=','base64');
        await page.locator('.ec-tryon-slot-card.is-model .ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'model.png',mimeType:'image/png',buffer:image});
        await page.locator('.ec-tryon-slot-card.is-model img').waitFor();
        await page.locator('[data-add-tryon-model]').click();
        await page.locator('[data-add-tryon-model]').click();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-empty-model').count(),2,'每次点击添加按钮都应创建空上传卡');
        await page.locator('.ec-tryon-slot-card.is-empty-model').nth(1).locator('[data-reference-type-inline]').dblclick();
        await page.locator('.ec-tryon-slot-card.is-empty-model').nth(1).locator('.ec-reference-type-inline-input').fill('第二位模特');
        await page.locator('.ec-tryon-slot-card.is-empty-model').nth(1).locator('.ec-reference-type-inline-input').press('Enter');
        await page.locator('.ec-tryon-slot-card.is-empty-model').nth(1).locator('.ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'model-two.png',mimeType:'image/png',buffer:image});
        assert.match(await page.locator('.ec-tryon-slot-card.is-model').nth(1).locator('[data-reference-type-inline]').textContent(),/第二位模特/);
        await page.locator('.ec-tryon-slot-card.is-empty-model .ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'model-three.png',mimeType:'image/png',buffer:image});
        await page.locator('[data-tryon-model-index]').nth(2).waitFor();
        assert.equal(await page.locator('[data-tryon-model-index]').count(),3);
        await page.locator('[data-tryon-model-index="1"]').click();
        assert.equal(await page.locator('[data-tryon-model-index="1"]').getAttribute('aria-pressed'),'true');
        await page.locator('.ec-tryon-slot-card.is-model.is-active [data-reference-type-inline]').dblclick();
        await page.locator('.ec-tryon-slot-card.is-model.is-active .ec-reference-type-inline-input').fill('都市青年模特');
        await page.locator('.ec-tryon-slot-card.is-model.is-active .ec-reference-type-inline-input').press('Enter');
        await page.locator('[data-tryon-model-description="1"]').fill('保持这位模特的面部和身形');
        const selectedModelUrl = await page.locator('.ec-tryon-model-select[aria-pressed="true"] img').getAttribute('src');
        const modelLayout = await page.locator('.ec-tryon-closet-grid').evaluate(element => {
            const cards = [...element.querySelectorAll(':scope > .ec-tryon-slot-card.is-model')];
            return {count:cards.length, maxRight:Math.max(...cards.map(card => card.getBoundingClientRect().right)), maxBottom:Math.max(...cards.map(card => card.getBoundingClientRect().bottom)), viewport:innerWidth, height:innerHeight};
        });
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-multiple-models.png'});
        assert.equal(modelLayout.count,3,'三位模特应直接平铺在操作区');
        assert.equal(await page.locator('.ec-tryon-slot-card.is-add-model').count(),1,'添加按钮卡应跟在最后一张模特卡后');
        assert.ok(modelLayout.maxRight <= modelLayout.viewport, '模特卡片应完整显示在工作台内');
        assert.ok(modelLayout.maxBottom <= modelLayout.height, '添加模特卡片应和其他模特在首屏完整显示');
        const flatStage = await page.locator('.ec-tryon-materials').evaluate(element => {
            const work = element.getBoundingClientRect();
            const intro = element.querySelector('.ec-tryon-step-intro').getBoundingClientRect();
            const stage = element.querySelector('.ec-tryon-stage').getBoundingClientRect();
            return {border:getComputedStyle(element).borderTopWidth,background:getComputedStyle(element).backgroundColor,introAbove:intro.bottom < stage.top,introLeft:intro.left < stage.left,centerDelta:Math.abs((stage.left + stage.right - work.left - work.right)/2)};
        });
        assert.equal(flatStage.border,'0px','操作区不应再有外层卡片边框');
        assert.equal(flatStage.background,'rgba(0, 0, 0, 0)','操作区不应再有外层卡片底色');
        assert.ok(flatStage.introAbove && flatStage.introLeft && flatStage.centerDelta < 12,'说明文字应在左上，卡片组应居中');
        assert.equal(await page.locator('[data-tryon-step-back]').count(),0);
        const firstArrow = await page.locator('.ec-tryon-materials').evaluate(element => {
            const card = element.querySelector('.ec-tryon-slot-card:last-child').getBoundingClientRect();
            const arrow = element.querySelector('[data-tryon-step-next]').getBoundingClientRect();
            return {clear:arrow.left >= card.right - 1,round:getComputedStyle(element.querySelector('[data-tryon-step-next]')).borderRadius};
        });
        assert.ok(firstArrow.clear,'右侧箭头不应遮挡添加模特卡');
        assert.equal(firstArrow.round,'50%');
        await page.locator('[data-tryon-model-remove="2"]').click();
        assert.equal(await page.locator('[data-tryon-model-index]').count(),2);
        assert.equal(await page.locator('[data-tryon-model-index="1"]').getAttribute('aria-pressed'),'true','删除其他模特时应保留当前选择');
        const remainingModelUrl = await page.locator('.ec-tryon-model-select[aria-pressed="true"] img').getAttribute('src');
        await page.locator('[data-tryon-step-next]').click();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-model').count(),0);
        assert.equal(await page.locator('[data-tryon-step-back]').count(),1);
        assert.equal(await page.locator('[data-tryon-step-next]').count(),1);
        await page.locator('[data-tryon-step-back]').click();
        assert.equal(await page.locator('[data-tryon-model-index]').count(),2);
        assert.equal(await page.locator('.ec-tryon-model-select[aria-pressed="true"] img').getAttribute('src'),remainingModelUrl);
        await page.locator('[data-tryon-step-next]').click();
        await page.locator('.ec-tryon-slot-card.is-outfit .ec-upload-slot').first().click();
        await page.locator('#fileInput').setInputFiles({name:'top.png',mimeType:'image/png',buffer:image});
        await page.locator('.ec-tryon-slot-card.is-outfit img').first().waitFor();
        await page.locator('[data-add-tryon-card="1"]').click();
        assert.equal(await page.locator('[data-tryon-wardrobe-role="shoes"]').count(),1,'添加服饰应先展开新的上传卡');
        const upper = page.locator('[data-tryon-wardrobe-role="upper_garment"]');
        await upper.locator('[data-reference-type-inline]').dblclick();
        await upper.locator('.ec-reference-type-inline-input').fill('定制西装上衣');
        await upper.locator('.ec-reference-type-inline-input').press('Enter');
        assert.equal(await upper.locator('.ec-tryon-media-card > .ec-tryon-type-row').count(),1,'类型下拉应在上传卡片内部底部');
        await upper.locator('[data-tryon-description-role]').fill('保留米白色面料与翻领结构');
        assert.ok(await upper.locator('[data-tryon-description-role]').evaluate(element => document.activeElement === element),'直接输入描述时应保持焦点');
        await page.locator('[data-tryon-drag-handle="upper_garment"]').dragTo(page.locator('[data-tryon-wardrobe-role="lower_garment"]'));
        assert.equal(await page.locator('.ec-tryon-slot-card.is-outfit').first().getAttribute('data-tryon-wardrobe-role'),'lower_garment');
        assert.equal((await page.locator('.ec-tryon-slot-card.is-outfit .ec-tryon-card-kicker b').allTextContents()).slice(0,3).join(','),'02,03,04','拖拽后左上角序号应随位置更新');
        await page.locator('[data-tryon-wardrobe-role="lower_garment"] .ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'trousers.png',mimeType:'image/png',buffer:image});
        await page.locator('[data-tryon-wardrobe-role="shoes"] .ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'loafers.png',mimeType:'image/png',buffer:image});
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-outfit-add-card.png'});
        await page.locator('[data-tryon-step-next]').click();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-fabric-detail').count(),1);
        await page.locator('[data-add-tryon-card="2"]').click();
        const extra = page.locator('[data-tryon-wardrobe-role="tryon_extra_1"]');
        assert.equal(await extra.count(),1,'添加调整参考应创建独立空上传卡');
        await extra.locator('.ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'detail.png',mimeType:'image/png',buffer:image});
        await extra.locator('img').first().waitFor();
        await extra.locator('[data-tryon-detail-target]').selectOption('upper_garment');
        await extra.locator('[data-reference-type-inline]').dblclick();
        await extra.locator('.ec-reference-type-inline-input').fill('领口纹理特写');
        await extra.locator('.ec-reference-type-inline-input').press('Enter');
        await extra.locator('[data-tryon-description-role]').fill('只参考领口织法，不改变服装版型');
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-tune-extra-card.png'});
        await page.locator('[data-tryon-step-next]').click();
        assert.equal(await page.locator('[data-tryon-step-next]').count(),0);
        assert.equal(await page.locator('[data-tryon-step-back]').count(),1);
        assert.equal(await page.locator('[data-tryon-plan-prompt],.ec-tryon-prompt-plan').count(),0);
        assert.equal(await page.locator('.ec-tryon-generation-models .ec-tryon-generation-card').count(),1);
        assert.equal(await page.locator('.ec-tryon-generation-model-strip button').count(),2);
        assert.equal(await page.locator('.ec-tryon-generation-models .is-model-hero.is-selected').count(),1);
        assert.equal(await page.locator('.ec-tryon-generation-outfit .ec-tryon-generation-card').count(),4);
        assert.equal(await page.locator('.ec-tryon-generation-card input').count(),0,'生成页不应常驻描述编辑框');
        assert.equal(await page.locator('.ec-tryon-generation-note').count(),0,'生成页不应展示替代描述文字控件');
        const typeButtonStyle = await page.locator('.ec-tryon-generation-outfit .ec-reference-type-button').first().evaluate(button => ({border:getComputedStyle(button).borderTopWidth,background:getComputedStyle(button).backgroundColor}));
        assert.notEqual(typeButtonStyle.border,'0px','生成页类型选择应保留原有卡片控件外观');
        assert.notEqual(typeButtonStyle.background,'rgba(0, 0, 0, 0)');
        const generationLayout = await page.locator('.ec-tryon-generation-references').evaluate(element => {
            const model=element.querySelector('.is-model-hero img').getBoundingClientRect();
            const references=[...element.querySelectorAll('.ec-tryon-generation-outfit .ec-tryon-generation-card')].map(card => card.getBoundingClientRect());
            return {modelRight:model.right,modelHeight:model.height,referenceLeft:Math.min(...references.map(rect => rect.left)),referenceHeight:references[0].height,rows:new Set(references.map(rect => Math.round(rect.top))).size};
        });
        assert.ok(generationLayout.modelRight < generationLayout.referenceLeft && generationLayout.modelHeight > generationLayout.referenceHeight,'生成页左侧应为模特大图，右侧应为小卡片');
        assert.equal(generationLayout.rows,2,'右侧参考卡应按两排显示');
        await page.waitForFunction(() => [...document.querySelectorAll('.ec-tryon-generation-card img')].every(image => image.complete && image.naturalWidth > 0));
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-generation-references.png'});
        await page.locator('.ec-tryon-message-box [data-option="instruction"]').fill('保持肩线和裤脚形状');
        await page.locator('#generateButton').click();
        await page.locator('.ec-tryon-style-dialog').waitFor();
        assert.equal(calls.filter(item => item.path === '/api/ecommerce/tasks').length,0,'选择样式前不能提交生成任务');
        assert.equal(await page.locator('.ec-tryon-style-grid button').count(),2);
        await page.waitForFunction(() => [...document.querySelectorAll('.ec-tryon-style-grid img')].every(image => image.complete && image.naturalWidth > 0));
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-style-dialog.png'});
        await page.locator('[data-close-tryon-style]').click();
        assert.equal(calls.filter(item => item.path === '/api/ecommerce/tasks').length,0,'取消样式选择不应生成');
        await page.locator('#generateButton').click();
        await page.locator('[data-tryon-guide-style="editorial_silhouette"]').click();
        await page.waitForFunction(() => document.querySelector('[data-export-tryon-guide]'));
        await page.locator('.ec-result-panel.is-showing-guide .ec-tryon-guide-result img').waitFor();
        assert.equal(await page.locator('.ec-result-panel.is-showing-guide #resultWorkspace:visible').count(),0,'搭配卡完成后应取代右侧原预览');
        await page.locator('[data-tryon-result-view="tryon"]').click();
        assert.equal(await page.locator('#resultWorkspace:visible').count(),1,'仍可查看最终换衣图');
        await page.locator('[data-tryon-result-view="guide"]').click();
        const analyzeCall = calls.find(item => item.path === '/api/ecommerce/analyze');
        assert.equal(analyzeCall.body.inputs.filter(item => item.role === 'source').length,1);
        assert.equal(analyzeCall.body.inputs.find(item => item.role === 'source').url,selectedModelUrl);
        assert.match(analyzeCall.body.inputs.find(item => item.role === 'source').label,/都市青年模特/);
        assert.equal(analyzeCall.body.inputs.find(item => item.role === 'source').instruction,'保持这位模特的面部和身形');
        assert.match(analyzeCall.body.inputs.find(item => item.role === 'upper_garment').label,/定制西装上衣/);
        assert.equal(analyzeCall.body.inputs.find(item => item.role === 'upper_garment').instruction,'保留米白色面料与翻领结构');
        assert.match(analyzeCall.body.inputs.find(item => item.reference_id === 'tryon_extra_1').label,/领口纹理特写/);
        assert.equal(analyzeCall.body.inputs.find(item => item.reference_id === 'tryon_extra_1').instruction,'只参考领口织法，不改变服装版型');
        assert.equal(analyzeCall.body.inputs.find(item => item.reference_id === 'tryon_extra_1').detail_target_id,'upper_garment');
        const taskCalls = calls.filter(item => item.path === '/api/ecommerce/tasks');
        assert.equal(taskCalls.length,2,'开始生成应提交最终换衣图和搭配卡两个任务');
        assert.equal(taskCalls[0].body.operation,'try_on');
        assert.equal(taskCalls[0].body.count,1);
        assert.equal(taskCalls[0].body.options.instruction,'保持肩线和裤脚形状');
        assert.ok(taskCalls[0].body.inputs.findIndex(item => item.role === 'lower_garment') < taskCalls[0].body.inputs.findIndex(item => item.role === 'upper_garment'),'请求顺序应与拖拽后的卡片顺序一致');
        const guideCall = taskCalls[1];
        assert.equal(guideCall.body.operation,'universal');
        assert.equal(guideCall.body.options.prompt_policy,'free');
        assert.equal(guideCall.body.aspect_ratio,'4:5');
        assert.equal(guideCall.body.inputs[0].role,'subject');
        assert.match(guideCall.body.options.instruction,/STYLE A — FASHION SILHOUETTE/);
        assert.match(guideCall.body.options.instruction,/保持肩线和裤脚形状/);
        assert.equal(await page.locator('#analysisPreview:visible').count(),0);
        assert.ok(calls.some(item => item.path === '/api/ecommerce/analyze'));
        await page.locator('[data-tryon-guide-format]').selectOption('jpeg');
        const downloadPromise = page.waitForEvent('download');
        await page.locator('[data-export-tryon-guide]').click();
        assert.match((await downloadPromise).suggestedFilename(),/\.jpg$/);
        await page.waitForTimeout(3500);
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-guide-demo.png',fullPage:true});
        await page.locator('.ec-tryon-stepbar [data-tryon-step="1"]').click();
        await page.locator('[data-add-tryon-card="1"]').click();
        assert.equal(await page.locator('[data-tryon-wardrobe-role="accessory"]').count(),1);
        await page.locator('[data-add-tryon-card="1"]').click();
        const extraOutfit = page.locator('[data-tryon-wardrobe-role="tryon_extra_2"]');
        assert.equal(await extraOutfit.count(),1,'预置服饰槽用完后仍可添加独立上传卡');
        await extraOutfit.locator('[data-tryon-reference-type]').selectOption('upper_garment');
        await extraOutfit.locator('.ec-upload-slot').click();
        await page.locator('#fileInput').setInputFiles({name:'extra-top.png',mimeType:'image/png',buffer:image});
        await extraOutfit.locator('img').first().waitFor();
        await page.locator('.ec-tryon-stepbar [data-tryon-step="3"]').click();
        assert.equal(await page.locator('.ec-tryon-generation-outfit .ec-tryon-generation-card').count(),5);
        await page.locator('#generateButton').click();
        await page.locator('[data-tryon-guide-style="editorial_model"]').click();
        await page.waitForFunction(() => document.querySelector('#generateButton:not(.submitting)'));
        assert.match(calls.filter(item => item.path === '/api/ecommerce/tasks').at(-1).body.options.instruction,/STYLE B — REAL MODEL EDITORIAL/);
        const extraOutfitRequest = calls.filter(item => item.path === '/api/ecommerce/analyze').at(-1).body.inputs.find(item => item.reference_id === 'tryon_extra_2');
        assert.equal(extraOutfitRequest.role,'upper_garment');
        const saved = JSON.parse(await page.evaluate(() => localStorage.getItem('studio_ecommerce_settings_v2')));
        assert.ok(saved.options.try_on.extra_slots.some(item => item.id === 'tryon_extra_2'));
        assert.match(saved.workspaces.try_on.inputs.upper_garment.custom_type_label,/定制西装上衣/);
        assert.equal(saved.workspaces.try_on.inputs.source.instruction,'保持这位模特的面部和身形');
        await page.locator('.ec-tryon-stepbar [data-tryon-step="1"]').click();
        assert.equal(await page.locator('[data-tryon-wardrobe-role="tryon_extra_2"]').count(),1,'新增上传卡应在步骤往返后保留');
        assert.match(await page.locator('[data-tryon-wardrobe-role="upper_garment"] [data-reference-type-inline]').textContent(),/定制西装上衣/);
        assert.match(await page.locator('[data-tryon-wardrobe-role="upper_garment"] [data-tryon-description-role]').inputValue(),/保留米白色面料/);
        await page.locator('[data-remove-tryon-extra="tryon_extra_2"]').click();
        assert.equal(await page.locator('[data-tryon-wardrobe-role="tryon_extra_2"]').count(),0);
        await page.locator('.ec-tryon-stepbar [data-tryon-step="0"]').click();
        assert.match(await page.locator('.ec-tryon-slot-card.is-model.is-active [data-reference-type-inline]').textContent(),/都市青年模特/);
        await page.locator('[data-add-tryon-model]').click();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-empty-model').count(),1);
        await page.locator('[data-remove-pending-model="0"]').click();
        assert.equal(await page.locator('.ec-tryon-slot-card.is-empty-model').count(),0);
        await page.locator('[data-tryon-model-remove="1"]').click();
        assert.equal(await page.locator('[data-tryon-model-index]').count(),1);
        assert.equal(await page.locator('[data-tryon-model-index="0"]').getAttribute('aria-pressed'),'true','删除当前模特后应选中剩余模特');
        await page.setViewportSize({width:520,height:900});
        const narrowCards = await page.locator('.ec-tryon-closet-grid').evaluate(element => [...element.querySelectorAll(':scope > .ec-tryon-slot-card')].every(card => card.getBoundingClientRect().right <= innerWidth));
        assert.ok(narrowCards,'窄屏模特卡片不应超出视口');
        const narrowArrow = await page.locator('.ec-tryon-materials').evaluate(element => ({
            cardBottom:element.querySelector('.ec-tryon-slot-card.is-add-model').getBoundingClientRect().bottom,
            arrowTop:element.querySelector('[data-tryon-step-next]').getBoundingClientRect().top,
        }));
        assert.ok(narrowArrow.arrowTop >= narrowArrow.cardBottom,'窄屏箭头应在卡片下方，避免遮挡上传');
        await page.locator('[data-tryon-step-next]').scrollIntoViewIfNeeded();
        await page.screenshot({path:'.codex-tmp/ecommerce-tryon-model-cards-narrow.png',fullPage:true});
        await page.locator('.ec-tryon-stepbar [data-tryon-step="1"]').click();
        const columns = await page.locator('.ec-tryon-closet-grid').evaluate(element => getComputedStyle(element).gridTemplateColumns.split(' ').length);
        assert.equal(columns,1,'窄屏服饰步骤应为单列');
        console.log('ecommerce guided try-on and outfit guide passed');
    } finally { await browser.close(); }
})().catch(error => {console.error(error);process.exitCode=1;});
