"""Build the portable video-generation training page from the Leopard canvas evidence."""
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / '案例' / '视频生成培训-20260921'
OUT = SOURCE / 'index.html'

PAGE = r'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHIYING · 视频生成教程</title><style>
:root{--paper:#f6eee4;--panel:#faf2e7;--card:#fffaf4;--control:#f7efe5;--ink:#332d28;--muted:#766f68;--line:rgba(91,74,54,.15);--accent:#9a6636;--contrast:#fff9f0}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.7 'Microsoft YaHei',sans-serif}header{padding:38px 5vw 30px;border-bottom:1px solid var(--line);background:var(--panel)}main{max-width:1440px;margin:auto;padding:30px 5vw 68px}h1{font-size:clamp(34px,5vw,62px);line-height:1.2;margin:8px 0 18px}h2{font-size:27px;line-height:1.35;margin:0 0 16px}.eyebrow{font-size:11px;font-weight:700;letter-spacing:2px;color:var(--accent)}.lead{max-width:760px;color:var(--muted);font-size:18px}.tabs{display:flex;gap:8px;overflow:auto;padding:16px 0}.tabs button{white-space:nowrap;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--ink);padding:9px 15px;cursor:pointer}.tabs button[aria-selected=true]{background:var(--accent);color:var(--contrast)}.panel[hidden]{display:none}.case{padding:25px;margin:20px 0;background:var(--card);border:1px solid var(--line);border-radius:8px}.two,.three{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.three{grid-template-columns:repeat(3,minmax(0,1fr))}.canvas-shot{display:block;width:100%;border:1px solid var(--line);border-radius:8px}.caption{color:var(--muted);font-size:13px;margin:10px 0 0}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:18px}.flow article{position:relative;padding:16px;background:var(--panel);border:1px solid var(--line);border-radius:8px}.flow article+article:before{content:'→';position:absolute;left:-17px;top:40%;font-size:22px;color:var(--accent)}.flow b{display:block;font-size:16px}.flow small{color:var(--muted)}.compare{overflow:auto}.compare table{width:100%;border-collapse:collapse;min-width:680px}.compare th,.compare td{text-align:left;padding:15px;border-bottom:1px solid var(--line);vertical-align:top}.compare th{background:var(--panel)}.badge{display:inline-block;color:var(--accent);font-size:12px;font-weight:700;letter-spacing:1px}.diagram{background:#252321;border-radius:8px;overflow:hidden}.diagram svg{display:block;width:100%;min-width:720px;height:auto}.steps{display:grid;gap:12px}.steps article{display:grid;grid-template-columns:38px 1fr;gap:12px;padding:14px;background:var(--panel);border-radius:8px}.steps b{font-size:20px;color:var(--accent)}.note{padding:15px 18px;border-left:3px solid var(--accent);background:var(--panel);color:var(--muted)}@media(max-width:800px){header,main{padding-inline:22px}.two,.three{grid-template-columns:1fr}.flow{grid-template-columns:1fr}.flow article+article:before{content:'↓';left:50%;top:-21px}.diagram{overflow:auto}.case{padding:18px}}@media(prefers-reduced-motion:reduce){.flow-node,.signal{animation:none!important}}
:root[data-theme=dark]{color-scheme:dark;--paper:#1a1a1a;--panel:#1e1e1e;--card:#20201f;--control:#292928;--ink:#f0eee9;--muted:#a7a6a2;--line:rgba(255,255,255,.12);--accent:#d2d0cb;--contrast:#1d1d1c}:root[data-theme=dark] .diagram{background:#121212}:root[data-theme=dark] .flow article,:root[data-theme=dark] .steps article{background:var(--control)}
</style><script>try{const theme=localStorage.getItem('shiyin-training-theme');if(theme==='dark'||theme==='light')document.documentElement.dataset.theme=theme}catch{}</script></head><body><header><span class="eyebrow">03 / 视频生成</span><h1>把复杂视频流程<br>变成一条可管理的画布</h1><p class="lead">以“豹纹”画布工程为例：先把镜头拆清楚，再让每个分镜、资产和成片都保留可追溯的连接关系。适合销售讲清方案，也适合视频制作人员接手执行。</p></header><main>
<nav class="tabs" role="tablist"><button role="tab" data-tab="case" aria-selected="true">豹纹案例</button><button role="tab" data-tab="flow" aria-selected="false">复杂流程</button><button role="tab" data-tab="depth" aria-selected="false">深度视频复刻</button><button role="tab" data-tab="choose" aria-selected="false">三种入口怎么选</button><button role="tab" data-tab="steps" aria-selected="false">上手步骤</button></nav>
<section class="panel" id="case"><div class="case"><span class="badge">真实画布工程 · 豹纹 · 194 节点</span><h2>不是把几十个镜头堆在文件夹里</h2><p>画布把线稿分镜、生成出的角色和场景资产、已合成的镜头画面，以及按镜头组输出的视频并列呈现。任何一个结果都能顺着连线回看它来自哪个分镜、用了哪些资产。</p><img class="canvas-shot" src="assets/leopard-canvas-project.png" alt="豹纹画布工程，包含多组黑白线稿、合成画面与视频镜头节点"><p class="caption">截图来自用户提供的已完成“豹纹”画布工程。画面中的黑白卡片是前期镜头规划，后续卡片承接资产和画面，再向视频生成输出。</p></div><div class="two"><article class="case"><h2>销售怎么讲</h2><p>客户不是只买一次生成，而是买一条可复用的制作路径。确认一个镜头组后，可以替换角色、服装、场景或文案，再按组继续出片。</p></article><article class="case"><h2>制作怎么用</h2><p>先锁机位和动作，再锁资产，最后批量出视频。发现某一镜不对，只返工这一条支线，不影响已确认的其他镜头。</p></article></div></section>
<section class="panel" id="flow" hidden><div class="case"><span class="badge">核心制作链路</span><h2>四段式制作：先控制，再生成</h2><div class="flow"><article><b>01 生成线稿分镜</b><small>把镜头景别、人物位置、视线、动作和前后景先固定下来。</small></article><article><b>02 生成资产图</b><small>按角色、服装、道具、场景分别准备可复用的视觉资产。</small></article><article><b>03 分镜合成画面</b><small>把线稿、资产和需要的深度控制汇到每一镜，得到可审片的首帧。</small></article><article><b>04 按组生成视频</b><small>把已确认的镜头组送入生成视频节点，组内连续出片，逐镜回看。</small></article></div></div><div class="case diagram"><svg viewBox="0 0 1180 430" role="img" aria-label="从线稿分镜、资产图、分镜合成到按组生成视频的动画流程"><style>.label{font:600 20px 'Microsoft YaHei',sans-serif;fill:#f6eee4}.sub{font:14px 'Microsoft YaHei',sans-serif;fill:#bdb7ae}.box{fill:#37332e;stroke:#b77b42;stroke-width:2}.line{stroke:#b77b42;stroke-width:3;fill:none;stroke-dasharray:8 8}.flow-node{animation:jump 5s ease-in-out infinite}.n2{animation-delay:.7s}.n3{animation-delay:1.4s}.n4{animation-delay:2.1s}.signal{stroke-dashoffset:160;animation:dash 2.5s linear infinite}@keyframes dash{to{stroke-dashoffset:0}}@keyframes jump{0%,12%,100%{transform:translateY(0)}6%{transform:translateY(-8px)}}</style><path class="line signal" d="M255 216H355M535 216H645M825 216H925"/><g class="flow-node"><rect class="box" x="45" y="115" width="210" height="202" rx="12"/><rect x="70" y="145" width="160" height="86" fill="#ece6dc"/><path d="M90 210l35-34 22 18 29-38 35 54" fill="none" stroke="#332d28" stroke-width="4"/><text class="label" x="70" y="270">线稿分镜</text><text class="sub" x="70" y="296">机位 / 动作 / 空间</text></g><g class="flow-node n2"><rect class="box" x="355" y="115" width="180" height="202" rx="12"/><circle cx="405" cy="183" r="28" fill="#d9a96d"/><rect x="442" y="153" width="61" height="61" fill="#8e6343"/><text class="label" x="380" y="270">资产图</text><text class="sub" x="380" y="296">人 / 衣 / 景 / 道具</text></g><g class="flow-node n3"><rect class="box" x="645" y="115" width="180" height="202" rx="12"/><rect x="670" y="145" width="130" height="88" fill="#a76e48"/><circle cx="716" cy="181" r="24" fill="#e8c396"/><path d="M765 201q17-47 29 0" fill="#44332d"/><text class="label" x="670" y="270">分镜合成</text><text class="sub" x="670" y="296">审首帧后再开跑</text></g><g class="flow-node n4"><rect class="box" x="925" y="115" width="210" height="202" rx="12"/><rect x="950" y="145" width="160" height="86" fill="#525c69"/><path d="M1020 162l45 26-45 26z" fill="#f6eee4"/><text class="label" x="950" y="270">按组生成视频</text><text class="sub" x="950" y="296">组内批量 / 逐镜回看</text></g></svg></div><p class="note">关键动作是“首帧通过后再生成视频”。这让导演、客户或销售可以先确认构图和资产归属，避免把不正确的画面直接投入长视频生成。</p></section>
<section class="panel" id="depth" hidden><div class="case"><span class="badge">深度视频 · 精准复刻的空间骨架</span><h2>它复刻的是每一帧的空间关系，不是把原视频重新上色</h2><p>深度视频会逐帧把原视频转换为相对深度序列：近处更突出，远处更靠后；人物肢体、遮挡关系和镜头推进的层次被保留下来。把它接入下游的分镜合成或视频生成时，模型有一条连续的空间参照，可在替换人物、服装、场景风格时尽量保持原视频的机位、动作轨迹与前后遮挡。</p><div class="diagram"><svg viewBox="0 0 1180 390" role="img" aria-label="原视频逐帧转为深度视频并作为下游生成约束的动画"><style>.dlabel{font:600 20px 'Microsoft YaHei',sans-serif;fill:#f6eee4}.dsub{font:14px 'Microsoft YaHei',sans-serif;fill:#bdb7ae}.frame{fill:#3a3732;stroke:#b77b42;stroke-width:2}.person{fill:#dfb584}.depth-a{fill:#eeeeea}.depth-b{fill:#969696}.depth-c{fill:#373737}.cursor{animation:scan 3s ease-in-out infinite}@keyframes scan{0%,100%{transform:translateX(0)}50%{transform:translateX(128px)}}</style><text class="dlabel" x="55" y="45">原视频</text><g><rect class="frame" x="55" y="72" width="250" height="180" rx="10"/><rect x="70" y="88" width="220" height="145" fill="#766f62"/><circle class="person" cx="155" cy="136" r="22"/><path class="person" d="M155 158l-36 58h72z"/><path d="M200 91v142" stroke="#b77b42" stroke-width="3" class="cursor"/></g><text class="dlabel" x="436" y="45">逐帧相对深度</text><g><rect class="frame" x="410" y="72" width="250" height="180" rx="10"/><rect class="depth-c" x="425" y="88" width="220" height="145"/><path class="depth-b" d="M425 185q72-80 220-12v60H425z"/><circle class="depth-a" cx="510" cy="136" r="22"/><path class="depth-a" d="M510 158l-36 58h72z"/></g><text class="dlabel" x="790" y="45">下游生成约束</text><g><rect class="frame" x="765" y="72" width="360" height="180" rx="10"/><rect x="780" y="88" width="330" height="145" fill="#6b4d3e"/><circle cx="870" cy="136" r="22" fill="#e8c396"/><path d="M870 158l-36 58h72z" fill="#252321"/><path d="M960 110h120M960 145h100M960 180h125" stroke="#d7a979" stroke-width="8" stroke-linecap="round"/></g><path d="M315 162h75M670 162h85" stroke="#b77b42" stroke-width="4"/><path d="M380 151l16 11-16 11M745 151l16 11-16 11" fill="none" stroke="#b77b42" stroke-width="4"/><text class="dsub" x="55" y="300">动作、镜头运动、遮挡</text><text class="dsub" x="410" y="300">近 / 中 / 远层连续一致</text><text class="dsub" x="765" y="300">换视觉内容，尽量不换空间逻辑</text></svg></div><p class="note">“精准”指对原视频的构图、运动和空间关系提供更强约束，不代表任何模型都能逐像素、逐帧保证完全相同。先在首帧和短镜头核验人物轮廓、遮挡和镜头方向，再批量生成。</p></div></section>
<section class="panel" id="choose" hidden><div class="case"><span class="badge">选择入口</span><h2>三种视频能力，各自解决不同问题</h2><div class="compare"><table><thead><tr><th>能力</th><th>核心优势</th><th>适合何时用</th><th>基本用法</th></tr></thead><tbody><tr><td><b>视频生成节点</b></td><td>面向单镜头制作；分镜图、提示词、演员/服装/道具都能通过端口明确输入。</td><td>已经有一张确认的首帧，需要精修一个关键镜头。</td><td>连接分镜图，补充动作、镜头与节奏；需要角色一致性时再接演员、服装和道具端口。</td></tr><tr><td><b>生成视频节点</b></td><td>面向影视链路；自动读取分镜组，按镜头拆分并保留组内的生成记录。</td><td>多个镜头已经通过审核，要按组连续出片。</td><td>将“分镜合成”输出接到“生成视频”；设置模型、时长、画幅和分辨率，按组提交后逐镜回看。</td></tr><tr><td><b>无限画布的常规视频生成</b></td><td>最轻量，直接从画布的图片或视频资产发起，适合快速试镜和灵感探索。</td><td>还在找动作、气氛或模型表现，没有复杂资产管理需求。</td><td>选中画面或视频资产，添加视频生成；用一两张参考和简短提示先做短片测试。</td></tr></tbody></table></div></div></section>
<section class="panel" id="steps" hidden><div class="case"><span class="badge">实操顺序</span><h2>从豹纹案例复用到下一支片</h2><div class="steps"><article><b>1</b><div><strong>把已有参考视频或关键帧接入“生成线稿分镜”。</strong><br><span class="caption">只检查机位、人物数量、朝向、动作和前中后景是否正确。</span></div></article><article><b>2</b><div><strong>按角色、服装、道具、场景准备资产图。</strong><br><span class="caption">同一资产可复用到多镜，替换时只影响连接到它的镜头。</span></div></article><article><b>3</b><div><strong>用“分镜合成”得到每一镜的首帧。</strong><br><span class="caption">把线稿、资产和需要的深度图连接进去，先审首帧。</span></div></article><article><b>4</b><div><strong>需要高度保持原视频走位时，先生成并接入“深度视频”。</strong><br><span class="caption">重点检查人物边缘、遮挡切换和镜头推进是否贴合原片。</span></div></article><article><b>5</b><div><strong>确认一组首帧后，接入“生成视频”按组提交。</strong><br><span class="caption">出现问题只回到对应镜头的分镜或资产节点修正，再单独重跑。</span></div></article></div></div></section>
</main><script>const tabs=[...document.querySelectorAll('[data-tab]')],panels=[...document.querySelectorAll('.panel')];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.setAttribute('aria-selected',x===b));panels.forEach(p=>p.hidden=p.id!==b.dataset.tab);history.replaceState(null,'','#'+b.dataset.tab)});const initial=tabs.find(x=>x.dataset.tab===location.hash.slice(1));if(initial)initial.click();</script></body></html>'''

page = PAGE.replace(
    '</style>',
    '.visual{display:block;width:100%;margin-top:18px;aspect-ratio:16/9;object-fit:cover;border:1px solid var(--line);border-radius:8px}</style>',
    1,
)
page = page.replace(
    '</div><p class="note">关键动作是“首帧通过后再生成视频”。',
    '</div><img class="visual" src="assets/storyboard-planning.jpg" alt="分镜策划工作台，展示四个连续镜头构图"><p class="caption">配图示意：先把连续镜头排成可沟通的画面顺序，再逐镜进入资产合成与视频生成。</p></div><p class="note">关键动作是“首帧通过后再生成视频”。',
    1,
)
page = page.replace(
    '</svg></div><p class="note">“精准”指对原视频的构图、运动和空间关系提供更强约束，',
    '</svg></div><img class="visual" src="assets/depth-reconstruction.jpg" alt="原视频、灰度深度层和复刻结果的对照示意"><p class="caption">配图示意：深度层保留近中远关系与人物遮挡，为下游画面替换提供连续空间参照。</p><p class="note">“精准”指对原视频的构图、运动和空间关系提供更强约束，',
    1,
)
page = page.replace(
    '<section class="panel" id="flow" hidden><div class="case"><span class="badge">核心制作链路</span>',
    '<section class="panel" id="flow" hidden><div class="case"><span class="badge">前期资产准备</span><h2>三视图让资产在每个镜头里都认得出来</h2><p>从一个清晰正面参考开始，创建三视图补齐正、侧、背，再补充面料、道具或关键配饰细节。后续把它们分别接到角色、服装和道具端口，能减少同一主体在不同镜头中变形或换装的风险。</p><img class="visual" src="assets/asset-three-view.jpg" alt="角色正面、侧面、背面与材质道具参考组成的资产三视图板"><p class="caption">配图示意：三视图用于建立可复用的角色和造型参照，不需要每一镜从零描述人物外观。</p></div><div class="case"><span class="badge">核心制作链路</span>',
    1,
)
OUT.write_text(page, encoding='utf-8')
print(OUT)
